### ISSUE TITLE
Configuring and installing Tower Failure

### ISSUE THREAD

**Issue by jag-sandhu** [groovy-sky/azure#5]
Hi,
I have been following your guide, and script.sh seems to fail on 'Configuring and installing tower' I am getting:

"Configuring and installing Tower
(VMExtensionProvisioningError) VM has reported a failure when processing extension 'customScript'. Error message: "Enable failed: failed to execute command: command terminated with exit status=2
[stdout]

[stderr]
sed: can't read /etc/awx/installer/inventory: No such file or directory
sed: can't read /etc/awx/installer/inventory: No such file or directory
sed: can't read /etc/awx/installer/inventory: No such file or directory
"

More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot
(VMExtensionProvisioningError) VM has reported a failure when processing extension 'customScript'. Error message: "Enable failed: failed to execute command: command terminated with exit status=1
[stdout]

[stderr]
ERROR! the playbook: /etc/awx/installer/install.yml could not be found
"

More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot"

The rest on the script goes on to complete with no errors, but when trying to access AWX im getting a 502 Bad Gateway error. 

Any tips?  I tried manually creating the directory and re-running the script, but that fails with:

"Configuring and installing Tower
(VMExtensionProvisioningError) VM has reported a failure when processing extension 'customScript'. Error message: "Enable failed: failed to execute command: command terminated with exit status=4
[stdout]

[stderr]
sed: couldn't edit /etc/awx/installer/inventory: not a regular file
sed: couldn't edit /etc/awx/installer/inventory: not a regular file
sed: couldn't edit /etc/awx/installer/inventory: not a regular file
"

More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot
(VMExtensionProvisioningError) VM has reported a failure when processing extension 'customScript'. Error message: "Enable failed: failed to execute command: command terminated with exit status=1
[stdout]

[stderr]
ERROR! the playbook: /etc/awx/installer/install.yml could not be found
"

More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot"

**Comment by groovy-sky** [comment]
Hi.
Thanks for info. Will try to check and troubleshoot the script.

**Comment by groovy-sky** [comment]
Fixed. Try now. Default password is MjXYQ4Cegf1dCnXpo
